Jenkinsfile_CNP
Testing addition of Camunda only upload pipeline. 
Actual upload can be tested on merge only (within Jenkins code, have commented out prod upload until tested here).
```
[ ] Yes
[ ] No
```
=> Camunda pipeline test

src/main/resources/mapCaseData_IA_Asylum.dmn
N/A
Update mapCaseData dmn table
```
[ ] Yes
[ x] No
```
=> Update mapCaseData dmn table

Jenkinsfile_CNP
Camunda pipeline changes have been merged, so don't need that branch now.
```
[ ] Yes
[ x] No
```
=> Use Jenkins libary master branch again as Jenkins code was merged

src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaGetTaskTest.java, src/integrationTest/resources/application-integration.yaml, src/main/resources/application.yaml, src/main/resources/getTaskId_IA_Asylum.dmn
RWA-180:
clean up old config
update dmn table with the task categories column
add integration tests
https://tools.hmcts.net/jira/browse/RWA-182
=> rwa-180: Add task categories to the task initiation dmn table

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RWA-242
Change s2s service name for a dedicated one
```
[ ] Yes
[x ] No
```
=> Change s2s service name for a dedicated one

src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaCancellationTaskTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaGetOverdueTaskTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaGetTaskTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaSetTaskCompleteTest.java, src/main/resources/wa-task-allowed-days-ia-asylum.dmn, src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn
https://tools.hmcts.net/jira/browse/RWA-221
RWA-221: Renaming camunda artifacts to match LLD
```
[ x] Yes
[ ] No
```
=> RWA-221: Rename camunda artefacts to match LLD

build.gradle, src/main/resources/wa-task-cancellation-ia-asylum.dmn
https://tools.hmcts.net/jira/browse/RWA-93
=> rwa-93 update DMN

src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RWA-286
=> cover submitAppeal dmn row scenarios

camunda-deployment.sh
Added tennant id to deployments
```
[ ] Yes
[ x] No
```
=> Added tennant id to deployments

charts/ia-task-configuration/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-356
Bumping java chart version
```
[ ] Yes
[x ] No
```
=> bumping java chart version

config/owasp/suppressions.xml
Remove redundant suppressions
```
[ ] Yes
[ x] No
```
=> Remove suppressions

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iataskconfiguration/Application.java
Remove Hystryx and suppression
```
[ ] Yes
[ x] No
```
=> Remove Hystryx and suppression

src/main/resources/wa-task-cancellation-ia-asylum.dmn
=> removed extra double quote

src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaTaskInitiationTest.java, src/main/resources/wa-task-initiation-ia-asylum.dmn
Correct dmn row for processApplication
```
[ ] Yes
[x ] No
```
=> Correct dmn row for processApplication

src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaTaskInitiationTest.java, src/main/resources/wa-task-initiation-ia-asylum.dmn
https://tools.hmcts.net/jira/browse/RWA-376
Added new column in Task Initiation DMN
```
[ ] Yes
[ x] No
```
=> Added new column delayDuration to calcuate delayUntil

src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaSetTaskCompleteTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaTaskCompletionTest.java, src/main/resources/wa-task-completion-ia-asylum.dmn
https://tools.hmcts.net/jira/browse/RWA-467
Correct event type names and add tests to cover all scenarios
```
[ ] Yes
[ x] No
```
=> RWA-467: Correct event type names and add tests to cover all scenarios

charts/ia-task-configuration/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-496
Bump hmctspublic java chart version
```
[ ] Yes
[x ] No
```
=> RWA-496: Bump hmctspublic java chart version

src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaCancellationTaskTest.java
https://tools.hmcts.net/jira/browse/RWA-490
=> add some more scenarios to the warning dmn test

src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaTaskCompletionTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iataskconfiguration/CamundaTaskConfigurationTest.java, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn
https://tools.hmcts.net/jira/browse/RWA-514
RWA-514: Correct variables naming strategy to camel case
```
[ ] Yes
[x ] No
```
=> RWA-514: Correct variables naming strategy to camel case

build.gradle
https://tools.hmcts.net/jira/browse/RWA-498
Replaced with JitPack dependencies
```
[ ] Yes
[x ] No
```
=> Replaced with JitPack dependencies

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RWA-534
```
[ ] Yes
[ x] No
```
=> replaced requestHearingRequirements initiation event

build.gradle, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RWA-563
=> remove rows and update tests

src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java
https://tools.hmcts.net/jira/browse/RWA-528
```
[ ] Yes
[x ] No
```
=> Added warningCode and warningText columns for Cancellation DMN

build.gradle, src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
Refactor initiation Dmn table to implement support for multiple categories.
```
[ ] Yes
[x ] No
```
=> RWA-532: Support for multiple categories without dummy events

build.gradle, src/main/resources/wa-task-completion-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/RWA-595
=> update dmn table

Jenkinsfile_CNP
Add Auto sync of branches with master for demo and perftest
```
[ ] Yes
[x ] No
```
=> Add Auto sync of branches with master for demo and perftest

Jenkinsfile_CNP
Change import to point to or to test changes for syncWithMaster()
```
[ ] Yes
[ x] No
```
=> Update Jenkinsfile_CNP to point to latest changes

Jenkinsfile_CNP, build.gradle, src/main/resources/wa-task-completion-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/RWA-557
```
[ ] Yes
[x ] No
```
=> Added empty rows for the events in completion DMN

Jenkinsfile_CNP, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RWA-634
=> remove dmn columns

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RWA-596
=> add new DMN rule

build.gradle
=> Tomcat version cve fix

build.gradle, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
[RWA-585](https://tools.hmcts.net/jira/browse/RWA-585)
```
[ ] Yes
[X ] No
```
=> RWA-585 Update task configuration to include case management category

build.gradle, charts/ia-task-configuration/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-433
=> upgrade springboot to 2.4 ver

src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-736
Add columns to permissions dmn to support release 2 auto-assignment based on priority
```
[ ] Yes
[x ] No
```
=> RWA-736: Release 2 Auto-assignment

build.gradle, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RWA-615
```
[ ] Yes
[x ] No
```
=> Updated Task Initiation DMN to accept appealType as Json

build.gradle, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-737
=> AC 2 - tribunal caseworker

src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-814
Correct DMNS based on new acceptance criteria
```
[ ] Yes
[ ] No
```
=> feat:Correct DMNS based on new acceptance criteria (RWA-814)

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-830
Worktype was missing for reviewAdditionalEvidence added as part of RWA-830
```
[ ] Yes
[x ] No
```
=> RWA-830: add Worktype for reviewAdditionalEvidence

src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-958
Add missing scenarios
```
[ ] Yes
[x ] No
```
=> RWA-958: Add missing permissions

src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-902
Add additional role mapping for permissions dmn
```
[ ] Yes
[ ] No
```
=> feat:Add additional role mapping for permissions dmn (RWA-902)

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-4969
=> add initiation DMN changes and unit tests

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
[RWA-943](https://tools.hmcts.net/jira/browse/RWA-943)
https://tools.hmcts.net/jira/browse/RWA-943
```
[ ] Yes
[ X] No
```
=> RWA-943 Populate Description attribute on tasks

src/main/resources/wa-task-allowed-days-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskAllowedDaysTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RWA-722
Change description
feat:Remove group from dmn
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ ] No
=> feat:Remove Group column from dmns(RWA-722)

src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-1017
```
[ ] Yes
[x ] No
```
=> RWA-1017: Updated authorisations 'IA' to numerical value

src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RWA-924
Add case access category
```
[ ] Yes
[ ] No
```
=> feat:Add case access category(RWA-924)

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
[RWA-836](https://tools.hmcts.net/jira/browse/RWA-836)
[RWA-836](https://tools.hmcts.net/jira/browse/RWA-836)
```
[ ] Yes
[ X] No
```
=> RWA-836 Update workflow API ready for EXUI consumption

src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-5377
```
[ ] Yes
[x] No
```
=> RIA-5377: Fix issue with task cancellation dmn file

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
[RWA-1104](https://tools.hmcts.net/jira/browse/RWA-1104)
[RWA-1104](https://tools.hmcts.net/jira/browse/RWA-1104)
```
[ ] Yes
[ X] No
```
=> RWA-1104 ADMINISTRATOR role_category to ADMIN

charts/ia-task-configuration/Chart.yaml
https://tools.hmcts.net/jira/browse/RIA-5503
```
[ ] Yes
[x] No
```
=> RIA-5503: Upgrade base helm charts to latest

config/owasp/suppressions.xml
=> update suppressions list

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
[RIA-6101](https://tools.hmcts.net/jira/browse/RIA-6101)
- Added 'updatePaymentStatus' with state 'appealSubmitted' for task 'reviewTheAppeal' when:
- appealType is HU, EA
- appealType is PA and paAppealTypePaymentOption is 'payNow'
```
[ ] Yes
[x] No
```
=> RIA-6101 Add updatePaymentStatus for reviewTheAppeal task

config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn
https://tools.hmcts.net/jira/browse/RIA-6177
Update the DMN file and Add EUSS appeal type to the list .
```
[ ] Yes
[ x] No
```
=> Added appealtype EUSS

config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn
Reverts hmcts/ia-task-configuration#219
=> Revert "Added appealtype EUSS"

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
=> RIA-6268 RoleAssignmentId added and auto allocate false

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
RIA-6259
```
[ ] Yes
[ ] No
```
=> RIA-6259 Change URL and category for access requests

config/owasp/suppressions.xml, src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RIA-6243
https://tools.hmcts.net/jira/browse/RIA-6244
Added a reconfiguration section to dmn files. 
After editAppeal and editAppealAfterSubmit events are triggered the data will be reconfigured to the most up to date data.
```
[ ] Yes
[x ] No
```
=> Added reconfiguration to name and location

config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn
https://tools.hmcts.net/jira/browse/RIA-6177
Updates to include EUSS in scope 
```
[ ] Yes
[X ] No
```
=> Updates to include EUSS in scope 

config/owasp/suppressions.xml, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6704
Fix to remove unclaim permission
```
[ ] Yes
[ X] No
```
=> Ria 6704 fix

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
Merge R3.5 changes to master branch
Merge R3.5 changes to master branch
```
[ ] Yes
[X ] No
```
=> WA 3.5 Master <- R3.5 - DO NOT MERGE

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6717
Added adaReviewTheAppeal task
```
[ ] Yes
[ x ] No
```
=> RIA-6717 Added adaReviewTheAppeal

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6714
Added ADA - Make an Application tasks for LO and Judge
```
[ ] Yes
[ x ] No
```
=> Ria 6714 add ada make an application tasks

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6725
Added  ADA follow up tasks
```
[ ] Yes
[ x ] No
```
=> Ria 6725 add ada follow up tasks

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6725
Updated permission and config for adaFollowUpExtendedDirection
```
[ ] Yes
[ x ] No
```
=> RIA-6725 Update permission and config for adaFollowUpExtendedDirection

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6722
Added ADA upload additional evidence tasks
```
[ ] Yes
[ x ] No
```
=> RIA-6722 Added ADA upload additional evidence tasks

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
Updated isAdaFlag to boolean type with default value to false if there is no data.
```
[ ] Yes
[ x ] No
```
=> Changed isAda flag to boolean type

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6732
Added transfer out of ada task
```
[ ] Yes
[ x ] No
```
=> RIA-6732 Added transfer out of ADA task

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
Added Generate Decision And Reasons task
https://tools.hmcts.net/jira/browse/RIA-6727
```
[ ] Yes
[ x ] No
```
=> RIA-6727 Added Generate Decision And Reasons task

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6728
-add ADA when apply ftpa appellant respondent
```
[ ] Yes
[X] No
```
=> RIA 6728 add ada when apply ftpa appellant respondent

config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6726
-Add the Judge permission for hearing judge
```
[ ] Yes
[X] No
```
=> RIA-6726-add-ada-when-review-addendum-evidence-v2

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6729
Added uploadHomeOfficeAppealResponse event task
```
[ ] Yes
[ x ] No
```
=> RIA-6729 Added uploadHomeOfficeAppealResponse task

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6828
Added decide an application ADA task
```
[ ] Yes
[ ] No
```
=> Ria 6828 decide an application ada task

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6832
-Add ADA when decision and reasons started
```
[ ] Yes
[X] No
```
=> RIA-6832-add-ada-when-decision-reasons-started

src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6731
Added permissions for judge to reviewCaseMarkedUnsuitableForADA  task
```
[ ] Yes
[ x ] No
```
=> RIA-6731 Addede reviewCaseMarkedUnsuitableForADA task for judge

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-6828
Removed Transfer application type from adaEditListing task
```
[ ] Yes
[ x ] No
```
=> RIA-6828 Removed Transfer application type from adaEditListing task

src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6828
Added execute permission to LO for adaEditListing
```
[ ] Yes
[ x ] No
```
=> RIA-6828 Added execute permission to LO for adaEditListing

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6835
Added adaAllocateHearingJudge task for ADA submitAppeal
```
[ ] Yes
[ x ] No
```
=> RIA-6835 Added adaAllocateHearingJudge task for ADA submitAppeal

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-6829
-update the post event state for new ADA task "ADA-Create Hearing Bundle" in task initiation file and unit test
```
[ ] Yes
[X] No
```
=> RIA-6829 add ada list case when create hearing bundle v2

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6831
-add ADA when generate customise hearing bundle
```
[ ] Yes
[X] No
```
=> RIA 6831 add ADA when generate customise hearing bundle

config/owasp/suppressions.xml, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/DmnDecisionTable.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-6344
Added new file task types for R4
```
[ ] Yes
[  x ] No
```
=> RIA-6344 Added new file task types for R4

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6469
Added review remission application task
```
[ ] Yes
[ x ] No
```
=> RIA-6469 Added review remission application task

config/owasp/suppressions.xml, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6474
Added  assign FTPA judge task
```
[ ] Yes
[ x ] No
```
=> RIA-6474 Added assign a FTPA Judge task for CTSC

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6473
Added List the case task for CTSC
```
[ ] Yes
[  x ] No
```
=> RIA-6473 Added List the case task for CTSC

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6472
Added mark as paid task for CTSC
```
[ ] Yes
[ x ] No
```
=> RIA-6472 Added markAsPaid task for CTSC

config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-6456
Update due date configuration for WAR4
```
[ ] Yes
[x] No
```
=> RIA-6456 Court Specific Calendar - Due Date Configuration

config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-6457
Update delay util configuration for WAR4
```
[ ] Yes
[x] No
```
=> RIA-6457 Court Specific Calendar - Delay Until Calculation

config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RIA-6457
Updated dueDateOrigin date format
```
[ ] Yes
[x] No
```
=> RIA-6457 Fixed dueDateOrigin date format

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-6472
Added due date skip non working days config
```
[ ] Yes
[ x ] No
```
=> RIA-6472 Added due date skip non working days config

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RIA-6457
Update reconfigure values
```
[ ] Yes
[ x ] No
```
=> RIA-6457 updated reconfigure values

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RIA-6968
Updated can reconfigure values
```
[ ] Yes
[ x ] No
```
=> RIA-6968 Update can reconfigure values

src/test/resources/extra-non-working-day-calendar.json
https://tools.hmcts.net/jira/browse/RIA-6456
Added extra test calendar
```
[ ] Yes
[ x ] No
```
=> RIA-6456 Added extra calendar

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-7028
updated dueDateIntervalDays and editListingChangeHC
```
[ ] Yes
[ x ] No
```
=> RIA-7028 updated dueDateIntervalDays and editListingChangeHC

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
Reverts hmcts/ia-task-configuration#309
=> Revert "RIA-7028 updated dueDateIntervalDays and editListingChangeHC"

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RIA-6456
Updated due dates for various tasks
```
[ ] Yes
[ x ] No
```
=> RIA-6456 Updated due dates for various tasks

config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
[Added FT for adaAllocateFTPAJudge suitable task
](https://tools.hmcts.net/jira/browse/RIA-6964)
Added adaAllocateHearingJudge task for ADA cases
```
[ ] Yes
[ x ] No
```
=> RIA-6964 Added adaAllocateHearingJudge task for ADA cases

src/test/resources/extra-non-working-day-calendar.json
https://tools.hmcts.net/jira/browse/RIA-7028
Added extra test non working day 27/04
```
[ ] Yes
[ x ] No
```
=> RIA-7028 Added extra test non working day

build.gradle, config/owasp/suppressions.xml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7132
Fixed suppressions
```
[ ] Yes
[x] No
```
=> RIA-7132 Removing suppressions

src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
Updates to fix permission issue for judge on ada review hearing bundle
Updates to fix permission issue for judge on ada review hearing bundle
```
[ ] Yes
[X ] No
```
=> Updates to fix permission issue for judge on ada review hearing bundle

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
Updates to remove ADA create hearing bundle task upon listing
Updates to remove ADA create hearing bundle task upon listing
```
[ ] Yes
[X ] No
```
=> Updates to remove ADA create hearing bundle task upon listing

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-6964
updated ADA-assignAFTPAJudge
```
[ ] Yes
[ x ] No
```
=> RIA-6964 updated ADA-assignAFTPAJudge

config/owasp/suppressions.xml, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RIA-6831
updated roleCategory for adaReviewHearingBundle
```
[ ] Yes
[ x ] No
```
=> RIA-6831 updated roleCategory for adaReviewHearingBundle

.github/renovate.json, Dockerfile, build.gradle, config/checkstyle/checkstyle.xml, config/owasp/suppressions.xml, gradle/wrapper/gradle-wrapper.properties, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-7920
Updated application type for make an application event
```
[ ] Yes
[ x ] No
```
=> RIA-7920 Updated application type for make an application event

build.gradle, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-5938
Updating DMN files and tests to remove processApplication and add separate ones for each application type
```
[ ] Yes
[x] No
```
=> RIA-5938 WA - Task 'Process Applications' to be broken into specific application types

config/owasp/suppressions.xml, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-7843
* Ensure 'editList' task is created only for list-assist cases on 'decideApplication' event
```
[ ] Yes
[x] No
```
=> RIA-7843 Granting application - Work allocation tasks are not created for List Assist cases

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-7790
- Trigged the "List the case" work allocation task when "Record adjournment details" event is completed with following condition:
1. if set "When did the adjournment happen?" question to "On the day of the hearing"
2. if  set "Can the case be relisted right away?" question to "Yes"
- Added the unit test for "List the case" work allocation task when "Record adjournment details" event is completed
```
[ ] Yes
[X] No
```
=> RIA-7790 list the case work allocation task is created when hearing is adjourned

.github/workflows/pr-title-validation.yml, build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DIAC-3
Updating suppressions
```
[ ] Yes
[ ] No
```
=> DIAC-003 updating-suppressions

config/owasp/suppressions.xml, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-7454
Added criteria to turn off work allocation task creation
```
[ ] Yes
[ x ] No
```
=> RIA-7454 Added criteria to turn off work allocation task creation

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-7453
Added EJP transfer down task
```
[ ] Yes
[ x ] No
```
=> RIA-7453 ejp transfer down task

config/owasp/suppressions.xml, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
Added CTSC admin and team leader permissions to cmrListed and cmrUpdated tasks
```
[ ] Yes
[x ] No
```
=> RIA-8034 - Added CTSC admin and team leader permissions

.github/renovate.json
https://tools.hmcts.net/jira/browse/DIAC-2
Updating renovate JSON to exclude certain packages from the generated PRs
```
[ ] Yes
[x] No
```
=> DIAC-002-Updating-Renovate-JSON-Excluding-Packages

config/owasp/suppressions.xml, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-7735
Added 'Review costs' TASK
```
[ ] Yes
[ ] No
```
=> RIA-7735 apply_for_costs

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-8391
RIA-8391 Rollback isIntegrated Yes/no to boolean
=> RIA-8391 Rollback isIntegrated Yes/no to boolean

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java
https://tools.hmcts.net/jira/browse/RIA-8400
```
[ ] Yes
[x] No
```
=> RIA-8400 Work allocation task for 'Change hearing type' application

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
[RIA-8231](https://tools.hmcts.net/jira/browse/RIA-8231)
- Trigger `listTheCase` when `isPanelRequired` and `isIntegrated` are both true during `reviewHearingRequirements` and `listCaseWithoutHearingRequirements`
```
[ ] Yes
[x] No
```
=> RIA-8231 Trigger listTheCase when isPanelRequired true

src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8292
- create reviewSetAsideDecisionApplication task when trigger makeAnApplication event
- create delayed followUpSetAsideDecision task when trigger decideAnApplication event
- update unit test
```
[ ] Yes
[X] No
```
=> RIA-8292 review set aside decision application wa task

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
[RIA-8625](https://tools.hmcts.net/jira/browse/RIA-8625)
- Added the `processApplicationChangeHearingType` task name to the list of names
- Added the `processApplicationChangeHearingType` task to autocompleting tasks
```
[ ] Yes
[x] No
```
=> RIA-8625 task name and auto completion

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8294
- create "Review appeal set aside under rule 35" WA task when trigger decideFtpaApplication event with "reheardRule35"
- set auto complete for  "reviewAppealSetAsideUnderRule35" WA task when trigger "requestNewHearingRequirements" event
- assign permission to LO
- allow 5 working days
- set work type to "Routine work"
- update the unit test
```
[ ] Yes
[X] No
```
=> RIA-8294 review appeal set aside under rule 35 wa task

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8295
- create "Review appeal set aside under rule 32" WA task when trigger "updateTribunalDecision" event with "underRule32"
- set auto complete for "reviewAppealSetAsideUnderRule32" WA task when trigger "requestNewHearingRequirements" event
- assign permission to LO
- allow 5 working days
- set work type to "Routine work"
- update the unit test
```
[ ] Yes
[X] No
```
=> RIA-8295 review appeal set aside under rule 32 WA task

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8286
Process fee refund - WA task
```
[ ] Yes
[x] No
```
=> RIA-8286 Process fee refund - WA task

src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8269
Added review draft appeal task
```
[ ] Yes
[ x ] No
```
=> RIA-8269 Added review draft appeal task

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/DIAC-112
```
[ ] Yes
[ ] No
```
=> DIAC-112 removing reviewAddendumEvidence from JUDICIAL user for DIAC-36

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-8901
Updated Application under rule 31 or rule 32 value
```
[ ] Yes
[ x ] No
```
=> RIA-8901 Updated Application under rule 31 or rule 32 value

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
=> DIAC-112 fix

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8272
Added printAndSendHoResponse task for NBC Admin
```
[ ] Yes
[ x ] No
```
=> RIA-8272 Added printAndSendHoResponse task for NBC Admin

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
Reverts hmcts/ia-task-configuration#396
=> DIAC-112 Revert "DIAC-112 removing reviewAddendumEvidence from JUDICIAL user for DIAC-36"

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8271
Print and send hearing requirements form WA-TASK
```
[ ] Yes
[x ] No
```
=> RIA-8271 Print and send hearing requirements form

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8273
Print and send hearing bundle - WA TASK
```
[ ] Yes
[x] No
```
=> RIA-8273 Print and send hearing bundle - WA TASK

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
=> RIA-TASK - REMITTED -> Master: DO NOT MERGE

src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
=> RIA-TASK - DLRM -> MASTER: DO NOT MERGE

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8276
Added WA task "Print and send decision corrected under rule 31"
```
[ ] Yes
[ x ] No
```
=> RIA-8276 Added WA task "Print and send decision corrected under rule 31"

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8296
Added WA task "Print and send decision corrected under rule 32"
```
[ ] Yes
[ x ] No
```
=> RIA-8296 Added WA task "Print and send decision corrected under rule 32"

charts/ia-task-configuration/Chart.yaml
https://tools.hmcts.net/jira/browse/DIAC-401
=> DIAC-401 Update charts Java Version

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8278
Added WA task "Print and send new HO evidence"
```
[ ] Yes
[ x ] No
```
=> RIA-8278 Added WA task "Print and send new HO evidence"

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
Publish isAdmin on event "sendDecisionAndReasons" for WA task
Added WA task "Print and send appeal decision and FTPA form"
```
[ ] Yes
[ x ] No
```
=> RIA-8274 Added WA task "Print and send appeal decision and FTPA form"

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-8275
Added WA task "Print and send FTPA decision"
```
[ ] Yes
[ x ] No
```
=> RIA-8275 Added WA task "Print and send FTPA decision"

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RIA-8904
```
[ ] Yes
[x] No
```
=> RIA-8904 Update WA Task Configuration files to enable Next Hearing Date

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/RIA-8904
```
[ ] Yes
[x] No
```
=> RIA-8904 Fix typo in Case data field 'hearingID'

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/RIA-9238
```
[ ] Yes
[X] No
```
=> RIA-9238 processFeeRefund task auto completed after refundConfirmation event

src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/RIA-9040
Add Reconfigure action for updateNextHearingInfo event
```
[ ] Yes
[ x] No
```
=> RIA-9040 - Add Reconfigure action for updateNextHearingInfo event

src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java
https://tools.hmcts.net/jira/browse/RIA-9267
Added events missing from refactoring
=> RIA-9267 update events

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
https://tools.hmcts.net/jira/browse/RIA-9159
Added reviewAriaRemissionApplication task
```
[ ] Yes
[ x ] No
```
=> RIA-9159 Added reviewAriaRemissionApplication task

src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
=> RIA-TASK - REFUND -> MASTER: DO NOT MERGE

src/main/resources/wa-task-allowed-days-ia-asylum.dmn, src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
Reverts hmcts/ia-task-configuration#442
=> Revert "RIA-9576 Merge refund dlrm fc"

src/main/resources/wa-task-allowed-days-ia-asylum.dmn, src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
=> RIA-TASK Merge with master

src/main/resources/wa-task-allowed-days-ia-asylum.dmn, src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
=> RIA-TASK - DLRM - FC -> Master: DO NOT MERGE

src/main/resources/wa-task-allowed-days-ia-asylum.dmn, src/main/resources/wa-task-cancellation-ia-asylum.dmn, src/main/resources/wa-task-completion-ia-asylum.dmn, src/main/resources/wa-task-configuration-ia-asylum.dmn, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/main/resources/wa-task-permissions-ia-asylum.dmn, src/main/resources/wa-task-types-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCancellationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskPermissionTest.java, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskTypesTest.java
Merge ICC and Migration FG to Master
```
[ ] Yes
[ x ] No
```
=> RIA-TASK Merge ICC and Migration FG to Master

infrastructure/variables.tf
=> DIAC-000 - update terraform

.github/workflows/pr-title-validation.yml, src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/DIAC-1057
Fix to stop creating duplicate review appeal tasks
```
[ ] Yes
[x] No
```
=> DIAC-1057 Fix duplicate reviewTheAppeal tasks

README.md, config/owasp/suppressions.xml
=> DIAC-000 test

infrastructure/main.tf
=> DIAC-000 - Remove vault secrets from terraform as they are being added in case-api

README.md
- Add developer's guide and update readme
=> DIAC-1206 Add developer's guide and update readme 

README.md, bin/upload-wa-dmn-preview.sh, bin/utils/idam-lease-service-token.sh
- Create a script that can upload work allocation DMN files to preview environment
=> DIAC-1266 Automate Work Allocation DMN File Upload to Preview Environment

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DIAC-1418
```
[ ] Yes
[ ] No
```
=> DIAC-1418 CVEs

src/main/resources/wa-task-completion-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/DIAC-1202
DIAC-1202 - updates to fix auto completion
```
[ ] Yes
[ ] No
```
=> DIAC-1202 - updates to fix auto completion

src/main/resources/wa-task-configuration-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskConfigurationTest.java
https://tools.hmcts.net/jira/browse/DIAC-1098
DIAC-1098 Updates to fix configuration for make application types
```
[ ] Yes
[ ] No
```
=> DIAC-1098 Updates to fix configuration for make application types

src/main/resources/wa-task-initiation-ia-asylum.dmn, src/test/java/uk/gov/hmcts/reform/iataskconfiguration/dmn/CamundaTaskInitiationTest.java
https://tools.hmcts.net/jira/browse/DIAC-1183
configure "migrateCase" event to progress appeals to "appealSubmitted" state and create WA task.
```
[ ] Yes
[x] No
```
=> DIAC-1183 DB Migration to fix appeals state
